name: build-highlightjs
run-name: Build Flix highlight.js package
on: [ push ]
jobs:
  build-highlightjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout highlight.js
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: highlightjs/highlight.js

      - name: Checkout latest highlight.js release
        run: git checkout `(git describe --tags)`

      - name: Checkout Flix language spec
        uses: actions/checkout@v3
        with:
          path: extra/flix

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test highlight.js
        run: |
          npm install
          node ./tools/build.js -t node
          npm run test-markup

      - name: Prune languages
        run: rm -r src/languages/*

      - name: Build highlight.js
        run: |
          npm install
          echo "Running npm audit fix"
          npm audit fix
          node ./tools/build.js -t all

      - name: List all files
        run: |
          pwd
          tree .
          ls -Alh

      - name: Upload Flix spec
        uses: actions/upload-artifact@v3
        with:
          name: flix.min.js
          path: extra/flix/dist/flix.min.js

      - name: Upload minimal Highlight.js with Flix bundled
        uses: actions/upload-artifact@v3
        with:
          name: highlight.min.js
          path: build/browser/highlight.min.js

      - name: Upload CDN distributable script.
        uses: actions/upload-artifact@v3
        with:
          name: highlight.cdn.min.js
          path: extra/flix/dist/flix.min.js
